import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import fs from 'node:fs';
import path from 'node:path';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// The typedoc-docusaurus-theme plugin writes a `typedoc-sidebar.cjs` into each
// generated API output directory (see docusaurus.config.ts's `plugins` array).
// It doesn't exist until `yarn generate-typedoc` has run at least once, so this
// falls back to an empty category rather than crashing a fresh checkout.
function loadGeneratedSidebar(pkg: string) {
  const sidebarPath = path.resolve(__dirname, `docs/api/${pkg}/typedoc-sidebar.cjs`);
  if (!fs.existsSync(sidebarPath)) {
    return [];
  }
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  return require(sidebarPath);
}

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'performance',
    {
      type: 'category',
      label: 'Getting Started',
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [{type: 'autogenerated', dirName: 'core-concepts'}],
    },
    {
      type: 'category',
      label: 'Routing & Controllers',
      items: [{type: 'autogenerated', dirName: 'routing-controllers'}],
    },
    {
      type: 'category',
      label: 'Models & Persistence',
      items: [{type: 'autogenerated', dirName: 'models-persistence'}],
    },
    {
      type: 'category',
      label: 'Auto CRUD Routes',
      items: [{type: 'autogenerated', dirName: 'auto-crud-routes'}],
    },
    {
      type: 'category',
      label: 'Default Routes',
      items: [{type: 'autogenerated', dirName: 'default-routes'}],
    },
    {
      type: 'category',
      label: 'Auth & RBAC',
      items: [{type: 'autogenerated', dirName: 'auth-rbac'}],
    },
    {
      type: 'category',
      label: 'Background Jobs',
      items: [{type: 'autogenerated', dirName: 'background-jobs'}],
    },
    {
      type: 'category',
      label: 'Events & Notifications',
      items: [{type: 'autogenerated', dirName: 'events-notifications'}],
    },
    {
      type: 'category',
      label: 'SSR React',
      items: [{type: 'autogenerated', dirName: 'ssr-react'}],
    },
    {
      type: 'category',
      label: 'CLI Reference',
      items: [{type: 'autogenerated', dirName: 'cli-reference'}],
    },
    {
      type: 'category',
      label: 'Testing',
      items: [{type: 'autogenerated', dirName: 'testing'}],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [{type: 'autogenerated', dirName: 'deployment'}],
    },
  ],

  // A separate sidebar (reached via its own navbar item) so ~150+ auto-generated
  // API reference pages don't drown out the hand-written guide sidebar above.
  apiSidebar: [
    'api/index',
    {
      type: 'category',
      label: '@rapidrest/core',
      link: {type: 'doc', id: 'api/core/index'},
      items: loadGeneratedSidebar('core'),
    },
    {
      type: 'category',
      label: '@rapidrest/service-core',
      link: {type: 'doc', id: 'api/service-core/index'},
      items: loadGeneratedSidebar('service-core'),
    },
  ],
};

export default sidebars;
