import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'performance',
    {
      type: 'category',
      label: 'Getting Started',
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [{type: 'autogenerated', dirName: 'core-concepts'}],
    },
    {
      type: 'category',
      label: 'Routing & Controllers',
      items: [{type: 'autogenerated', dirName: 'routing-controllers'}],
    },
    {
      type: 'category',
      label: 'Models & Persistence',
      items: [{type: 'autogenerated', dirName: 'models-persistence'}],
    },
    {
      type: 'category',
      label: 'Auto CRUD Routes',
      items: [{type: 'autogenerated', dirName: 'auto-crud-routes'}],
    },
    {
      type: 'category',
      label: 'Auth & RBAC',
      items: [{type: 'autogenerated', dirName: 'auth-rbac'}],
    },
    {
      type: 'category',
      label: 'Background Jobs',
      items: [{type: 'autogenerated', dirName: 'background-jobs'}],
    },
    {
      type: 'category',
      label: 'SSR React',
      items: [{type: 'autogenerated', dirName: 'ssr-react'}],
    },
    {
      type: 'category',
      label: 'CLI Reference',
      items: [{type: 'autogenerated', dirName: 'cli-reference'}],
    },
  ],
};

export default sidebars;
